import * as vscode from 'vscode';
import { PanelProvider } from '../vscode-utils/PanelProvider';

export class LlmBackgroundService implements vscode.Disposable {
  private _abortController: AbortController | null = null;
  private _disposables: vscode.Disposable[] = [];
  private _typingTimeout: NodeJS.Timeout | null = null;
  private _lastProcessedCode: string = '';

  constructor() {
    this._disposables.push(
      vscode.commands.registerCommand('vibecodeease.recordAccept', this.recordAccept.bind(this)),
      vscode.commands.registerCommand('vibecodeease.cancelAnalysis', this.cancelAnalysis.bind(this))
    );

    // Listen to native VS Code text changes
    this._disposables.push(
      vscode.workspace.onDidChangeTextDocument((e) => {
        // Only run if the AI panel is open and we're typing in a real file
        if (!PanelProvider.currentPanel || e.document.uri.scheme !== 'file') {
          return;
        }

        const currentCode = e.document.getText();
        if (currentCode === this._lastProcessedCode) {
          return;
        }

        // Debounce typing (1.5 seconds)
        if (this._typingTimeout) {
          clearTimeout(this._typingTimeout);
        }

        // Cancel any ongoing LLM processing
        this.cancelAnalysis();

        this._typingTimeout = setTimeout(() => {
          this._lastProcessedCode = currentCode;
          this.run3LLMPipeline(currentCode, e.document.uri);
        }, 1500);
      })
    );
  }

  public cancelAnalysis() {
    if (this._abortController) {
      this._abortController.abort();
      this._abortController = null;
    }
  }

  public async run3LLMPipeline(code: string, documentUri: vscode.Uri) {
    this.cancelAnalysis();
    this._abortController = new AbortController();
    const signal = this._abortController.signal;

    try {
      this.sendStageUpdate('Candidate Generation (LLM 1)...');
      await this.sleep(1000);
      if (signal.aborted) return;

      this.sendStageUpdate('Vector Reranking (DB Match)...');
      await this.sleep(800);
      if (signal.aborted) return;

      this.sendStageUpdate('Summarizing Preferences (LLM 2) & Finalizing (LLM 3)...');
      await this.sleep(1000);
      if (signal.aborted) return;

      const mockProposal = {
        id: Date.now().toString(),
        originalText: code,
        proposedText: code + '\n\n// Backend AI Suggestion: Refactored base on Vector DB preferences',
        explanation: 'Generated by the 3-LLM pipeline mock on the backend.',
        status: 'pending',
        documentUri: documentUri.toString()
      };

      if (PanelProvider.currentPanel) {
        PanelProvider.currentPanel.sendToWebview('aiProposalsComplete', { proposals: [mockProposal] });
      }

    } catch (e) {
      if (!signal.aborted && PanelProvider.currentPanel) {
        PanelProvider.currentPanel.sendToWebview('aiProposalsError', { error: String(e) });
      }
    }
  }

  public async recordAccept(proposal: any, codeBefore: string) {
    vscode.window.setStatusBarMessage('$(database) Vector DB: Saved Accept history', 3000);
    
    // Apply the proposal text directly to the native VS Code editor!
    if (proposal.documentUri) {
      const uri = vscode.Uri.parse(proposal.documentUri);
      const editor = vscode.window.visibleTextEditors.find(e => e.document.uri.toString() === uri.toString());
      
      if (editor) {
        const fullRange = new vscode.Range(
          editor.document.positionAt(0),
          editor.document.positionAt(editor.document.getText().length)
        );
        
        await editor.edit(editBuilder => {
          editBuilder.replace(fullRange, proposal.proposedText);
        });
        this._lastProcessedCode = proposal.proposedText;
      }
    }

    const newTrend = `Updated ${new Date().toLocaleTimeString()}: User prefers backend refactoring.`;
    if (PanelProvider.currentPanel) {
      PanelProvider.currentPanel.sendToWebview('personalizationUpdated', { trend: newTrend });
    }
  }

  private sendStageUpdate(stage: string) {
    if (PanelProvider.currentPanel) {
      PanelProvider.currentPanel.sendToWebview('aiStageUpdate', { stage });
    }
  }

  private sleep(ms: number) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  dispose() {
    if (this._typingTimeout) {
      clearTimeout(this._typingTimeout);
    }
    this.cancelAnalysis();
    this._disposables.forEach(d => d.dispose());
  }
}
