/**
 * @AI_AGENT_NOTE
 * The `InterventionMode` defines the Persona/Strategy the AI will use when analyzing and proposing changes.
 * - 'hinting': Focuses on education and minor points, avoiding large rewrites.
 * - 'silent_fixer': (Default) Quietly fixes minor issues like typos and lint errors.
 * - 'architect': Boldly suggests structural, large-scale changes.
 * 
 * WHY: This enables the "Git-like AI Workspace" to simulate different types of "collaborators" pushing changes to the workspace.
 */
export type InterventionMode = 'hinting' | 'silent_fixer' | 'architect';

export interface Proposal {
  id: string;
  originalText: string;
  proposedText: string;
  explanation: string;
  status: 'pending' | 'accepted' | 'rejected';
  documentUri?: string;
  /**
   * @AI_AGENT_NOTE
   * `isAiPush` distinguishes whether this Proposal was generated by the AI asynchronously pushing changes (true)
   * or simply from a manual/synchronous user sync (false or undefined).
   * 
   * ROLE: In the Git-like flow, `isAiPush=true` represents the AI committing and pushing to the remote AI branch,
   * while the user sits on their local branch. The UI uses this to display "AI Push" vs "User Sync".
   */
  isAiPush?: boolean;
}

export interface Settings {
  triggerMode: 'on-save' | 'interval-10s' | 'disabled';
  personalizationTrend: string;
  llmApiKey: string;
  llmModel: string;
  interventionMode?: InterventionMode;
}
